import type { Metadata, Viewport } from "next";
import { Instrument_Serif } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Analytics } from "@vercel/analytics/react";

import { ThemeProvider } from "@/components/theme-provider";

import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const instrument = Instrument_Serif({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#fff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${GeistSans.variable} ${instrument.variable} ${GeistMono.variable} dark bg-black text-neutral-400 antialiased font-sans`}
      >
        <Analytics />
        <ThemeProvider
          // forcedTheme="dark"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <div className="min-h-screen">
            <div className="md:max-w-2xl px-8 mx-auto flex flex-col gap-16 md:gap-24 py-16 md:py-28">
              {children}
            </div>
          </div>

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
