import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#fff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} text-black bg-white dark:text-white dark:bg-black font-sans`}
      >
        <div className="min-h-screen bg-white text-neutral-900">
          <div className="md:max-w-3xl px-8 mx-auto flex flex-col gap-16 md:gap-24 py-16 md:py-28">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
